FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY . .
RUN go mod tidy && go build -o /bin/api ./cmd/api

FROM alpine:3.22
WORKDIR /app
COPY --from=builder /bin/api /app/api

EXPOSE 8080
CMD ["/app/api"]
